# Generated by Django 5.2.6 on 2025-09-16 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id_candidato', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('formacao', models.TextField(blank=True, null=True)),
                ('experiencias', models.TextField(blank=True, null=True)),
                ('cursos', models.TextField(blank=True, null=True)),
                ('habilidades', models.TextField(blank=True, null=True)),
                ('link_portfolio', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('area_atuacao', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id_mensagem', models.AutoField(primary_key=True, serialize=False)),
                ('conteudo', models.TextField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='empresa.candidato')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='empresa.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id_notificacao', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='empresa.candidato')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='empresa.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id_relatorio', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='empresa.administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id_vaga', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('requisitos', models.TextField()),
                ('local', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('emprego', 'Emprego'), ('estagio', 'Estágio'), ('bolsa', 'Bolsa')], max_length=50)),
                ('remuneracao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carga_horaria', models.CharField(max_length=50)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='empresa.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id_candidatura', models.AutoField(primary_key=True, serialize=False)),
                ('data_candidatura', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('analise', 'Em análise'), ('selecionado', 'Selecionado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='empresa.candidato')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='empresa.vaga')),
            ],
        ),
    ]
